Repository ts-common/azure-js-dev-tools, pull requests merged in 2019-03, with the labels that each got.

#121 Allow multiple commit messages
  lib/git.ts
  package.json
  test/gitTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#122 Add GitHub.getCommit()
  lib/github.ts
  package.json
  test/githubTests.ts
  test/packageJsonTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#123 Add FakeRunner.onUnrecognizedCommand() method
  lib/run.ts
  package.json
  test/runTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#124 Add checkFileContains
  lib/checkEverything.ts
  lib/checkFileContains.ts
  lib/checkForOnlyCalls.ts
  lib/checkForSkipCalls.ts
  lib/checkPackageJsonVersion.ts
  lib/git.ts
  lib/index.ts
  package.json
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#125 Fix checkFileContains()
  lib/checkEverything.ts
  lib/checkFileContains.ts
  package.json
Labels: in progress

#126 Fix gitPush()
  lib/git.ts
  package.json
  test/gitTests.ts
Labels: in progress

#127 Extract logger to @azure/logger-ts package
  lib/arrays.ts
  lib/assertEx.ts
  lib/autorest.ts
  lib/blobStorage.ts
  lib/checkEverything.ts
  lib/checkFileContains.ts
  lib/checkForOnlyCalls.ts
  lib/checkForSkipCalls.ts
  lib/checkPackageJsonVersion.ts
  lib/commandLine.ts
  lib/compressor.ts
  lib/dependencies.ts
  lib/fileSystem2.ts
  lib/git.ts
  lib/github.ts
  lib/http.ts
  lib/index.ts
  lib/logger.ts
  lib/mvn.ts
  lib/node.ts
  lib/npm.ts
  lib/packageJson.ts
  lib/path.ts
  lib/run.ts
  lib/url.ts
  package.json
  test/loggerTests.ts
Labels: in progress

#135 Add create and close pull request methods
  lib/git.ts
  lib/github.ts
  lib/run.ts
  package.json
  test/githubTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#141 Fix createPullRequest() and add ForkedRepositoryBranch interface
  lib/git.ts
  lib/github.ts
  package.json
  test/gitTests.ts
  test/githubTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#159 Add body/description to github.createPullRequest() method
  lib/github.ts
  package.json
  test/githubTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#180 Add deleteLabel(), return created label from createLabel()
  lib/arrays.ts
  lib/github.ts
  package.json
  test/arraysTests.ts
  test/githubTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#187 Fix checks
  lib/checkEverything.ts
  lib/checkFileContains.ts
  lib/checkForOnlyCalls.ts
  lib/checkForSkipCalls.ts
  lib/checkPackageJsonVersion.ts
  lib/fileSystem2.ts
  package.json
  test/arraysTests.ts
  test/githubTests.ts
Labels: in progress

#194 Add BlobStorageAppendBlob with tests
  .scripts/checkEverything.ts
  fakeFile.txt
  lib/blobStorage.ts
  package.json
  test/blobStorageTests.ts
Labels: Started-Sprint-132, Unplanned-Sprint-132, in progress

#197 Add environmentVariables to RunOptions
  lib/run.ts
  package.json
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#198 Log environment variables before running a command
  lib/run.ts
  package.json
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#199 Improve/expand gitDiff() function and tests
  .gitignore
  .scripts/checkForUnstagedChanges.ts
  lib/checkEverything.ts
  lib/checkForUnstagedChanges.ts
  lib/git.ts
  lib/index.ts
  package.json
  test/gitTests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#200 Improve error checking in findFileInPath()
  lib/fileSystem2.ts
  package.json
  test/fileSystem2Tests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#201 No current folder in getFilesChangedFromFullDiff() should return rela…
  lib/git.ts
  package.json
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#202 Add Azure/logger-js to planning script
  .scripts/planning.ts
  package.json
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#203 Unify blob URL encoding
  lib/blobStorage.ts
  package.json
  test/blobStorageTests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#206 Return decoded blob URLs by default
  lib/blobStorage.ts
  package.json
  test/blobStorageTests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#207 Improve test coverage
  package.json
  test/pathTests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133, in progress

#208 Add deleteFolder() test and skip some githubTests
  .scripts/checkEverything.ts
  .scripts/checkForSkipCalls.ts
  package.json
  test/fileSystem2Tests.ts
  test/githubTests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133

#209 Add HTMLBuilder objects
  lib/htmlBuilder.ts
  package.json
  test/htmlBuilderTests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133

#210 Export htmlBuilder from index
  lib/index.ts
  package.json
Labels: Started-Sprint-133, Unplanned-Sprint-133

#211 Improve HTMLBuilder create functions
  lib/htmlBuilder.ts
  package.json
Labels: Started-Sprint-133, Unplanned-Sprint-133

#212 Add more features to HTMLBuilder
  lib/htmlBuilder.ts
  package.json
Labels: Started-Sprint-133, Unplanned-Sprint-133

#213 Finish with HTML builder for now
  lib/htmlBuilder.ts
  lib/index.ts
  lib/textBuilder.ts
  package.json
  test/htmlBuilderTests.ts
Labels: Started-Sprint-133, Unplanned-Sprint-133
