Repository ts-common/azure-js-dev-tools, pull requests merged in 2019-01, with the labels that each got.

#49 AzureDevOpsLogger should log errors to stdout by default
  lib/logger.ts
  package.json
  test/loggerTests.ts
Labels: Started-Sprint-129, Unplanned-Sprint-129

#50 Add commandLine functions, read verbose argument from command line
  lib/commandLine.ts
  lib/dependencies.ts
  lib/index.ts
  lib/logger.ts
  package.json
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress

#51 Add ignore-azure-js-dev-tools to dependencies
  lib/dependencies.ts
  package.json
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress

#52 Log warning instead of error if skipIsWarning is true
  lib/checkForSkipCalls.ts
  package.json
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress

#53 Add runAsync(), improve tests
  lib/assertEx.ts
  lib/node.ts
  lib/run.ts
  package.json
  test/assertExTests.ts
  test/nodeTests.ts
  test/runTests.ts
Labels: Planned-Sprint-129, Started-Sprint-129, in progress

#54 Add GitHub pull request webhook request body type
  lib/github.ts
  package.json
Labels: Planned-Sprint-129, Started-Sprint-129, in progress

#55 Add git clone function
  lib/git.ts
  package.json
Labels: Planned-Sprint-129, in progress

#57 Add Azure/swagger-to-sdk-ts to planning script
  .scripts/planning.ts
  package.json
Labels: Started-Sprint-129, Unplanned-Sprint-129, in progress

#58 Redesign github.ts, add additionalChecks to checkEverything.ts
  lib/assertEx.ts
  lib/checkEverything.ts
  lib/github.ts
  package.json
  test/githubTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#60 Add GitHubPullRequest.diff_url property
  lib/github.ts
  package.json
  test/githubTests.ts
Labels: Started-Sprint-130, Unplanned-Sprint-130, in progress

#61 Add GitHub.getPullRequest() and tests
  lib/assertEx.ts
  lib/github.ts
  package.json
  test/githubTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#62 Add http and url
  lib/http.ts
  lib/url.ts
  package.json
  test/githubTests.ts
  test/httpTests.ts
  test/urlTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#63 Update exports to include new modules
  lib/index.ts
  package.json
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#64 Add HTTPS support to NodeHttpClient and getDefaultHttpClient()
  lib/http.ts
  package.json
  test/httpTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#65 Handle redirects in NodeHttpClient
  lib/assertEx.ts
  lib/http.ts
  package.json
  test/httpTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#66 Add GitHubPullRequest.merge_commit_sha property
  lib/github.ts
  package.json
  test/githubTests.ts
  test/httpTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#67 Add options to gitClone()
  azure-pipelines.yml
  lib/git.ts
  package.json
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#68 Add getRootPath()
  lib/path.ts
  package.json
  test/pathTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#69 Add options to npmInstall()
  lib/npm.ts
  package.json
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#70 Improve skip and only checks
  lib/checkForOnlyCalls.ts
  lib/checkForSkipCalls.ts
  lib/common.ts
  package.json
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#71 Add Runner interface, remove mockResult and mockError from RunOptions
  lib/checkForSkipCalls.ts
  lib/git.ts
  lib/run.ts
  package.json
  test/gitTests.ts
  test/runTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#72 Extract and export npmExecutable
  lib/npm.ts
  package.json
  test/npmTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#73 Add tests for git and npm output and error capture
  lib/git.ts
  lib/npm.ts
  package.json
  test/gitTests.ts
  test/npmTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#74 Add autorest and try to fix nyc sourcemap problem
  azure-pipelines.yml
  lib/autorest.ts
  lib/common.ts
  lib/dependencies.ts
  lib/npm.ts
  lib/path.ts
  lib/run.ts
  package.json
  test/autorestTests.ts
  test/gitTests.ts
  test/mocha.opts
  test/pathTests.ts
  test/runTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#75 Export autorest module
  lib/index.ts
  package.json
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#76 Add npm run build to devops pipeline
  azure-pipelines.yml
  package.json
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#77 Fix captureOutput and captureError
  lib/run.ts
  package.json
  test/runTests.ts
Labels: in progress

#78 Add BlobStorage interface and tests
  .scripts/checkEverything.ts
  lib/blobStorage.ts
  lib/common.ts
  lib/index.ts
  package.json
  test/blobStorageTests.ts
  test/githubTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#79 Add getCompositeLogger() and tests
  lib/logger.ts
  package.json
  test/loggerTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#81 Add createFolder() function and tests
  lib/fileSystem2.ts
  package.json
  test/fileSystem2Tests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#82 Change Logger to be async
  lib/arrays.ts
  lib/logger.ts
  package.json
  test/loggerTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress

#83 Daschult/process log
  lib/autorest.ts
  lib/checkEverything.ts
  lib/checkPackageJsonVersion.ts
  lib/common.ts
  lib/dependencies.ts
  lib/git.ts
  lib/npm.ts
  lib/packageJson.ts
  lib/run.ts
  package.json
  test/autorestTests.ts
  test/gitTests.ts
  test/npmTests.ts
  test/packageJsonTests.ts
  test/runTests.ts
Labels: Planned-Sprint-130, Started-Sprint-130, in progress
